name: nightly
on:
  schedule:
    - cron: '14 3 * * *'
  push:
    branches:
      - "**"

jobs:
  binary:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: 🐙 Checkout GitHub repo (Also build submodule AntaREST)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Update submodule to latest commit of `dev`
        run: |
          cd antares_web
          git checkout dev
          git pull
          echo "Current commit: $(git log -1 --pretty=oneline)"
          cd ..

      - name: 💚 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - name: 💚 Install dependencies
        run: npm install
        working-directory: antares_web/webapp

      - name: 💚 Build webapp
        run: bash ./build-front.sh
        working-directory: scripts
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: 🐍 Install development dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r antares_web/requirements-dev.txt

      - name: 📦 Packaging
        run: bash ./package_antares_web.sh
        working-directory: scripts

      - name: 📜️ Copy changelog file
        run: |
          cp antares_web/docs/CHANGELOG.md dist/package/CHANGELOG.md

      - name: 📦 Archive Antares Desktop for Ubuntu
        # this is the only way to preserve file permission and symlinks
        if: matrix.os != 'windows-latest'
        run: zip -r --symlinks AntaresWeb.zip *
        working-directory: dist/package

      - name: 📦 Upload asset to release
        run: gh release upload AntaresWebDev dist/package/AntaresWeb.zip  --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
